Change location of role="navigation" in header
This should remove the following W3C validation Error:
Error: Bad value navigation for attribute role on element ul.

Notes:
https://awkawk.github.io/using_nav.html
http://www.w3.org/WAI/GL/wiki/Using_HTML5_nav_element#Example:The_.3Cnav.3E_element
Special mention to: "When support for HTML5 improves there may be no need to continue to add the ARIA role="navigation". ", for now it should help to achieve w3c 100% validation without errors and warnings.